refactor: change types in ipc_events to interfaces the reasoning behind using types here "These need to be strictly types and not interfaces like eslint is suggesting, no extra fields should be send via IPC." is flawed as "error TS2353: Object literal may only specify known properties" applies to interfaces as well and non-literals may specify unknown properties regardless of whether it is an interface or a type